// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gevtdlviuavzwwccztqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdldnRkbHZpdWF2end3Y2N6dHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyODMwMDYsImV4cCI6MjA3Mjg1OTAwNn0.xeJNB17oCJU6H7Q_vjec4amJNHDEMRmBU0xcjOx_40I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});